export const MenuCardsComplete = [
  {
    id: 'Expresso Tradicional',
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 11.99,
    image: 'Expresso',
    type: ['Tradicional'],
  },
  {
    id: 'Expresso Americano',
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 11.99,
    image: 'Americano',
    type: ['Tradicional'],
  },
  {
    id: 'Expresso Cremoso',
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 11.99,
    image: 'Expresso Cremoso',
    type: ['Tradicional'],
  },
  {
    id: 'Expresso Gelado',
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 11.99,
    image: 'Café Gelado',
    type: ['Tradicional', 'gelado'],
  },
  {
    id: 'Café com Leite',
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 11.99,
    image: 'Café com Leite',
    type: ['Tradicional', 'com leite'],
  },
  {
    id: 'Latte',
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 11.99,
    image: 'Latte',
    type: ['Tradicional', 'com leite'],
  },
  {
    id: 'Capuccino',
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 11.99,
    image: 'Capuccino',
    type: ['Tradicional', 'com leite'],
  },
  {
    id: 'Macchiato',
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 11.99,
    image: 'Macchiato',
    type: ['Tradicional', 'com leite'],
  },
  {
    id: 'Mocaccino',
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 11.99,
    image: 'Mocaccino',
    type: ['Tradicional', 'com leite'],
  },
  {
    id: 'Chocolate Quente',
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 11.99,
    image: 'Chocolate Quente',
    type: ['especial', 'com leite'],
  },
  {
    id: 'Cubano',
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 11.99,
    image: 'Cubano',
    type: ['especial', 'alcoólico', 'gelado'],
  },
  {
    id: 'Havaiano',
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 11.99,
    image: 'Havaiano',
    type: ['especial'],
  },
  {
    id: 'Árabe',
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 11.99,
    image: 'Árabe',
    type: ['especial'],
  },
  {
    id: 'Irlandês',
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 11.99,
    image: 'Irlandês',
    type: ['especial', 'alcoólico'],
  },
]
